set_property SRC_FILE_INFO {cfile:C:/Users/CST/Desktop/3-28/LAB5_LampCtrl138/LAB5_LampCtrl138.srcs/constrs_1/new/lamp_xdc.xdc rfile:../../../LAB5_LampCtrl138.srcs/constrs_1/new/lamp_xdc.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA10 [get_ports S1]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB10 [get_ports S2]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA13 [get_ports S3]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF24 [get_ports F]
