#switch
set_property IOSTANDARD LVCMOS33 [get_ports {s[0]}]				
set_property PACKAGE_PIN J15    [get_ports {s[0]}]                 
set_property IOSTANDARD LVCMOS33 [get_ports {s[1]}]				
set_property PACKAGE_PIN L16    [get_ports {s[1]}]                 
set_property IOSTANDARD LVCMOS33 [get_ports  s1]				
set_property PACKAGE_PIN M13    [get_ports  s1]                 
set_property IOSTANDARD LVCMOS33 [get_ports {s2[0]}]				
set_property PACKAGE_PIN R15    [get_ports {s2[0]}]                 
set_property IOSTANDARD LVCMOS33 [get_ports {s2[1]}]				
set_property PACKAGE_PIN R17     [get_ports {s2[1]}]                 
set_property IOSTANDARD LVCMOS33 [get_ports {s2[2]}]				
set_property PACKAGE_PIN T18     [get_ports {s2[2]}]                 
set_property IOSTANDARD LVCMOS33 [get_ports {I0[0]}]				
set_property PACKAGE_PIN U18    [get_ports {I0[0]}]                 
set_property IOSTANDARD LVCMOS33 [get_ports {I0[1]}]				
set_property PACKAGE_PIN R13    [get_ports {I0[1]}]                 
set_property IOSTANDARD LVCMOS18 [get_ports {I0[2]}]				
set_property PACKAGE_PIN T8    [get_ports {I0[2]}]                  
set_property IOSTANDARD LVCMOS18 [get_ports {I0[3]}]				
set_property PACKAGE_PIN U8    [get_ports {I0[3]}]                 
set_property IOSTANDARD LVCMOS33 [get_ports {I0[4]}]			
set_property PACKAGE_PIN R16    [get_ports {I0[4]}]                 
set_property IOSTANDARD LVCMOS33 [get_ports {I1[0]}]			
set_property PACKAGE_PIN T13    [get_ports {I1[0]}]                 
set_property IOSTANDARD LVCMOS33 [get_ports {I1[1]}]			
set_property PACKAGE_PIN H6     [get_ports {I1[1]}]                 
set_property IOSTANDARD LVCMOS33 [get_ports {I1[2]}]			
set_property PACKAGE_PIN U12    [get_ports {I1[2]}]                 
set_property IOSTANDARD LVCMOS33 [get_ports {I1[3]}]			
set_property PACKAGE_PIN U11    [get_ports {I1[3]}]                 
set_property IOSTANDARD LVCMOS33 [get_ports {I1[4]}]			
set_property PACKAGE_PIN V10    [get_ports {I1[4]}]  

set_property IOSTANDARD LVCMOS33 [get_ports {o_0[0]}]
set_property PACKAGE_PIN H17     [get_ports {o_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_0[1]}]
set_property PACKAGE_PIN K15    [get_ports {o_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_0[2]}]
set_property PACKAGE_PIN J13     [get_ports {o_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_0[3]}]
set_property PACKAGE_PIN N14    [get_ports {o_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_0[4]}] 			
set_property PACKAGE_PIN R18     [get_ports {o_0[4]}]  

		

		

		
